/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai4;

//import java.util.Locale;
//import java.util.ResourceBundle;
import java.util.*;
/**
 *
 * @author hv
 */
public class frmFindAir extends javax.swing.JFrame {

    /**
     * Creates new form frmFindAir
     */
    public frmFindAir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNgayDi = new javax.swing.JTextField();
        txtNgayVe = new javax.swing.JTextField();
        cbbDiemDi = new javax.swing.JComboBox();
        cbbDiemDen = new javax.swing.JComboBox();
        cbbNguoiLon = new javax.swing.JComboBox();
        cbbTreEm = new javax.swing.JComboBox();
        cbbEmBe = new javax.swing.JComboBox();
        lbDiemKhoiHanh = new javax.swing.JLabel();
        lbDiemDen = new javax.swing.JLabel();
        lbNgayDi = new javax.swing.JLabel();
        lbNgayVe = new javax.swing.JLabel();
        lbNguoiLon = new javax.swing.JLabel();
        lbTreEm = new javax.swing.JLabel();
        lbEmBe = new javax.swing.JLabel();
        btnTimVe = new javax.swing.JButton();
        lbLoaiVe = new javax.swing.JLabel();
        rdbMotChieu = new javax.swing.JRadioButton();
        rdbKhuHoi = new javax.swing.JRadioButton();
        lbTimVeMayBay = new javax.swing.JLabel();
        btnViet = new javax.swing.JButton();
        btnAnh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbbDiemDi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbDiemDen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbNguoiLon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbTreEm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbEmBe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbDiemKhoiHanh.setText("Điểm Khởi Hành");

        lbDiemDen.setText("Điểm Đến");

        lbNgayDi.setText("Ngày Đi");

        lbNgayVe.setText("Ngày Về");

        lbNguoiLon.setText("Người Lớn");

        lbTreEm.setText("Trẻ Em");

        lbEmBe.setText("Em Bé");

        btnTimVe.setText("Tìm Vé");

        lbLoaiVe.setText("Loại Vé");

        buttonGroup1.add(rdbMotChieu);
        rdbMotChieu.setText("Một Chiều");

        buttonGroup1.add(rdbKhuHoi);
        rdbKhuHoi.setText("Khứ Hồi");

        lbTimVeMayBay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTimVeMayBay.setText("TÌM VÉ MÁY BAY");

        btnViet.setText("Việt");
        btnViet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVietActionPerformed(evt);
            }
        });

        btnAnh.setText("Anh");
        btnAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDiemKhoiHanh)
                    .addComponent(lbDiemDen)
                    .addComponent(lbNgayDi)
                    .addComponent(lbNgayVe)
                    .addComponent(lbNguoiLon)
                    .addComponent(lbTreEm)
                    .addComponent(lbEmBe)
                    .addComponent(lbLoaiVe))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbDiemDi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbNguoiLon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbTreEm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbEmBe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayDi)
                            .addComponent(cbbDiemDen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayVe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(btnTimVe)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbMotChieu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(rdbKhuHoi)
                        .addGap(105, 105, 105))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnViet)
                .addGap(18, 18, 18)
                .addComponent(btnAnh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(lbTimVeMayBay)
                .addGap(206, 206, 206))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTimVeMayBay)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnViet)
                        .addComponent(btnAnh)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbLoaiVe)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbMotChieu)
                        .addComponent(rdbKhuHoi)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbDiemDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiemKhoiHanh))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbDiemDen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDiemDen))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNgayDi))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNgayVe))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbNguoiLon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimVe)))
                    .addComponent(lbNguoiLon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTreEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTreEm))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbEmBe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmBe))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVietActionPerformed
        // TODO add your handling code here:
        Locale currentLocale;//=new Locale("vi","VN");
        currentLocale=new Locale("vi","VN");
        ResourceBundle messages;
        messages=ResourceBundle.getBundle("Bai4/resource_vi_VN",currentLocale);
        lbLoaiVe.setText(messages.getString("S1"));
        rdbMotChieu.setText(messages.getString("S2"));
        rdbKhuHoi.setText(messages.getString("S3"));
        lbDiemKhoiHanh.setText(messages.getString("S4"));
        lbDiemDen.setText(messages.getString("S5"));
        lbNgayDi.setText(messages.getString("S6"));
        lbNgayVe.setText(messages.getString("S7"));
        lbNguoiLon.setText(messages.getString("S8"));
        lbTreEm.setText(messages.getString("S9"));
        lbEmBe.setText(messages.getString("S10"));
        btnTimVe.setText(messages.getString("S11"));
        lbTimVeMayBay.setText(messages.getString("S12"));
        
      //  lbNguoiLon.sette
        
    }//GEN-LAST:event_btnVietActionPerformed

private void btnAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhActionPerformed
// TODO add your handling code here:
    // TODO add your handling code here:
        Locale currentLocale;//=new Locale("vi","VN");
        currentLocale=new Locale("en","US");
        ResourceBundle messages;
        messages=ResourceBundle.getBundle("Bai4/resource_en_US",currentLocale);
        lbLoaiVe.setText(messages.getString("S1"));
        rdbMotChieu.setText(messages.getString("S2"));
        rdbKhuHoi.setText(messages.getString("S3"));
        lbDiemKhoiHanh.setText(messages.getString("S4"));
        lbDiemDen.setText(messages.getString("S5"));
        lbNgayDi.setText(messages.getString("S6"));
        lbNgayVe.setText(messages.getString("S7"));
        lbNguoiLon.setText(messages.getString("S8"));
        lbTreEm.setText(messages.getString("S9"));
        lbEmBe.setText(messages.getString("S10"));
        btnTimVe.setText(messages.getString("S11"));
        lbTimVeMayBay.setText(messages.getString("S12"));
    
}//GEN-LAST:event_btnAnhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFindAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFindAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFindAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFindAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFindAir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnh;
    private javax.swing.JButton btnTimVe;
    private javax.swing.JButton btnViet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbbDiemDen;
    private javax.swing.JComboBox cbbDiemDi;
    private javax.swing.JComboBox cbbEmBe;
    private javax.swing.JComboBox cbbNguoiLon;
    private javax.swing.JComboBox cbbTreEm;
    private javax.swing.JLabel lbDiemDen;
    private javax.swing.JLabel lbDiemKhoiHanh;
    private javax.swing.JLabel lbEmBe;
    private javax.swing.JLabel lbLoaiVe;
    private javax.swing.JLabel lbNgayDi;
    private javax.swing.JLabel lbNgayVe;
    private javax.swing.JLabel lbNguoiLon;
    private javax.swing.JLabel lbTimVeMayBay;
    private javax.swing.JLabel lbTreEm;
    private javax.swing.JRadioButton rdbKhuHoi;
    private javax.swing.JRadioButton rdbMotChieu;
    private javax.swing.JTextField txtNgayDi;
    private javax.swing.JTextField txtNgayVe;
    // End of variables declaration//GEN-END:variables
}
