/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai3;

/**
 *
 * @author hv
 */
public class FrmPhuongTienGiaoThong extends javax.swing.JFrame {

    /**
     * Creates new form FrmPhuongTienGiaoThong
     */
    XeHoi xh;
    TauThuy tt;
    public FrmPhuongTienGiaoThong() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        txtHangSX = new javax.swing.JTextField();
        txtquangDuongXeHoi = new javax.swing.JTextField();
        txtThoigianXeHoi = new javax.swing.JTextField();
        txtSoLitXeHoi = new javax.swing.JTextField();
        txtvanTocXeHoi = new javax.swing.JTextField();
        txtTieuThuNhienLieuXeHoi = new javax.swing.JTextField();
        btnTinhVanTocXeHoi = new javax.swing.JButton();
        btnTinhtieuThuNhienLieuXeHoi = new javax.swing.JButton();
        try {
            jPanel2 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "Bai3.FrmPhuongTienGiaoThong_jPanel2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTrongLuong = new javax.swing.JTextField();
        txtSucTai = new javax.swing.JTextField();
        txtVanTocXuoiDong = new javax.swing.JTextField();
        txtVanTocNguocDong = new javax.swing.JTextField();
        txtTieuHaoNhienLieu = new javax.swing.JTextField();
        btnTinhVanTocTauThuy = new javax.swing.JButton();
        btnTieuThuNhienLieuTauThuy = new javax.swing.JButton();
        txtvanTocTauthuy = new javax.swing.JTextField();
        txtTieuHaoNhienLieuTauThuy = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtquangDuongTauThuy = new javax.swing.JTextField();
        txtthoiGianTauThuy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsoLitTauThuy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);

        jLabel1.setText("Tên Xe");

        jLabel2.setText("Hãng Sản Xuất");

        jLabel3.setText("Quãng Đường");

        jLabel4.setText("Thời Gian");

        jLabel5.setText("Số Lít");

        txtHangSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHangSXActionPerformed(evt);
            }
        });

        txtSoLitXeHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLitXeHoiActionPerformed(evt);
            }
        });

        txtvanTocXeHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvanTocXeHoiActionPerformed(evt);
            }
        });

        txtTieuThuNhienLieuXeHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTieuThuNhienLieuXeHoiActionPerformed(evt);
            }
        });

        btnTinhVanTocXeHoi.setText("Tính Vận tốc");
        btnTinhVanTocXeHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhVanTocXeHoiActionPerformed(evt);
            }
        });

        btnTinhtieuThuNhienLieuXeHoi.setText("Tính Tiêu Thụ Nhiên Liệu");
        btnTinhtieuThuNhienLieuXeHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhtieuThuNhienLieuXeHoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenXe)
                            .addComponent(txtHangSX)
                            .addComponent(txtquangDuongXeHoi)
                            .addComponent(txtThoigianXeHoi)
                            .addComponent(txtSoLitXeHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTinhVanTocXeHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTinhtieuThuNhienLieuXeHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvanTocXeHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtTieuThuNhienLieuXeHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHangSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtquangDuongXeHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtThoigianXeHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvanTocXeHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhVanTocXeHoi))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLitXeHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnTinhtieuThuNhienLieuXeHoi)
                    .addComponent(txtTieuThuNhienLieuXeHoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Xe Hơi", jPanel1);

        jLabel6.setText("Trọng Lượng");

        jLabel7.setText("Sức Tải");

        jLabel8.setText("Vận Tốc Xuôi Dòng");

        jLabel9.setText("Vận Tốc Ngược Dòng");

        jLabel10.setText("Tiêu Hao Nhiên Liệu");

        txtVanTocXuoiDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVanTocXuoiDongActionPerformed(evt);
            }
        });

        txtVanTocNguocDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVanTocNguocDongActionPerformed(evt);
            }
        });

        btnTinhVanTocTauThuy.setText("Tính Vận Tốc");
        btnTinhVanTocTauThuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhVanTocTauThuyActionPerformed(evt);
            }
        });

        btnTieuThuNhienLieuTauThuy.setText("Tính Tiêu Thụ Nhiên Liệu");
        btnTieuThuNhienLieuTauThuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTieuThuNhienLieuTauThuyActionPerformed(evt);
            }
        });

        txtTieuHaoNhienLieuTauThuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTieuHaoNhienLieuTauThuyActionPerformed(evt);
            }
        });

        jLabel11.setText("Quãng Đường");

        jLabel12.setText("Thời Gian");

        jLabel13.setText("Số Lít");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtVanTocXuoiDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSucTai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTrongLuong, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtthoiGianTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtquangDuongTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtsoLitTauThuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVanTocNguocDong, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTieuHaoNhienLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTinhVanTocTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTieuThuNhienLieuTauThuy))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvanTocTauthuy, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(txtTieuHaoNhienLieuTauThuy, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTrongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtquangDuongTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSucTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtthoiGianTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtVanTocXuoiDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtsoLitTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtVanTocNguocDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTinhVanTocTauThuy)
                    .addComponent(txtvanTocTauthuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTieuHaoNhienLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btnTieuThuNhienLieuTauThuy)
                    .addComponent(txtTieuHaoNhienLieuTauThuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tàu Thủy", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHangSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHangSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHangSXActionPerformed

    private void txtSoLitXeHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLitXeHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLitXeHoiActionPerformed

    private void txtvanTocXeHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvanTocXeHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvanTocXeHoiActionPerformed

    private void txtTieuThuNhienLieuXeHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTieuThuNhienLieuXeHoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTieuThuNhienLieuXeHoiActionPerformed

    private void btnTinhtieuThuNhienLieuXeHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhtieuThuNhienLieuXeHoiActionPerformed
        // TODO add your handling code here:
         double quangDuong=Double.parseDouble(txtquangDuongXeHoi.getText());
        double soLit=Double.parseDouble(txtSoLitXeHoi.getText());
        int thoiGian=Integer.parseInt(txtThoigianXeHoi.getText());
        xh=new XeHoi();
        txtTieuThuNhienLieuXeHoi.setText(xh.tinhTieuThuNhienLieu(quangDuong, soLit)+"");
    }//GEN-LAST:event_btnTinhtieuThuNhienLieuXeHoiActionPerformed

    private void txtVanTocNguocDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVanTocNguocDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVanTocNguocDongActionPerformed

    private void txtVanTocXuoiDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVanTocXuoiDongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVanTocXuoiDongActionPerformed

    private void txtTieuHaoNhienLieuTauThuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTieuHaoNhienLieuTauThuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTieuHaoNhienLieuTauThuyActionPerformed

    private void btnTinhVanTocXeHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhVanTocXeHoiActionPerformed
        // TODO add your handling code here:
        String tenXe=txtTenXe.getText();
        String hangSX=txtHangSX.getText();
        double quangDuong=Double.parseDouble(txtquangDuongXeHoi.getText());
        double soLit=Double.parseDouble(txtSoLitXeHoi.getText());
        int thoiGian=Integer.parseInt(txtThoigianXeHoi.getText());
        xh=new XeHoi();//(tenXe, hangSX);
        txtvanTocXeHoi.setText(xh.tinhVanToc(quangDuong, thoiGian)+"");
        //txtTieuThuNhienLieuXeHoi.setText(xh.tinhTieuThuNhienLieu(quangDuong, soLit)+"");
    }//GEN-LAST:event_btnTinhVanTocXeHoiActionPerformed

    private void btnTinhVanTocTauThuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhVanTocTauThuyActionPerformed
        // TODO add your handling code here:
        double quangDuong=Double.parseDouble(txtquangDuongTauThuy.getText());
        double vantocXuoidong=Double.parseDouble(txtVanTocXuoiDong.getText());
        double vantocNguocDong=Double.parseDouble(txtVanTocNguocDong.getText());
        double tieuHaoNhienLieu=Double.parseDouble(txtTieuHaoNhienLieu.getText());
        int thoiGian=Integer.parseInt(txtthoiGianTauThuy.getText());
        double soLit=Double.parseDouble(txtsoLitTauThuy.getText());
        String trongLuong=txtTrongLuong.getText();
        String sucTai=txtSucTai.getText();
        tt=new TauThuy(trongLuong, sucTai, vantocXuoidong, vantocNguocDong, tieuHaoNhienLieu);
        txtvanTocTauthuy.setText(tt.tinhVanToc(quangDuong, thoiGian)+"");
        
    }//GEN-LAST:event_btnTinhVanTocTauThuyActionPerformed

private void btnTieuThuNhienLieuTauThuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTieuThuNhienLieuTauThuyActionPerformed
// TODO add your handling code here:
        double quangDuong=Double.parseDouble(txtquangDuongTauThuy.getText());
        double vantocXuoidong=Double.parseDouble(txtVanTocXuoiDong.getText());
        double vantocNguocDong=Double.parseDouble(txtVanTocNguocDong.getText());
        double tieuHaoNhienLieu=Double.parseDouble(txtTieuHaoNhienLieu.getText());
        int thoiGian=Integer.parseInt(txtthoiGianTauThuy.getText());
        double soLit=Double.parseDouble(txtsoLitTauThuy.getText());
        String trongLuong=txtTrongLuong.getText();
        String sucTai=txtSucTai.getText();
        tt=new TauThuy(trongLuong, sucTai, vantocXuoidong, vantocNguocDong, tieuHaoNhienLieu);
        txtTieuHaoNhienLieuTauThuy.setText(tt.tinhTieuThuNhienLieu(quangDuong, soLit)+"");
}//GEN-LAST:event_btnTieuThuNhienLieuTauThuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTienGiaoThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTienGiaoThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTienGiaoThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhuongTienGiaoThong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPhuongTienGiaoThong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTieuThuNhienLieuTauThuy;
    private javax.swing.JButton btnTinhVanTocTauThuy;
    private javax.swing.JButton btnTinhVanTocXeHoi;
    private javax.swing.JButton btnTinhtieuThuNhienLieuXeHoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtHangSX;
    private javax.swing.JTextField txtSoLitXeHoi;
    private javax.swing.JTextField txtSucTai;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtThoigianXeHoi;
    private javax.swing.JTextField txtTieuHaoNhienLieu;
    private javax.swing.JTextField txtTieuHaoNhienLieuTauThuy;
    private javax.swing.JTextField txtTieuThuNhienLieuXeHoi;
    private javax.swing.JTextField txtTrongLuong;
    private javax.swing.JTextField txtVanTocNguocDong;
    private javax.swing.JTextField txtVanTocXuoiDong;
    private javax.swing.JTextField txtquangDuongTauThuy;
    private javax.swing.JTextField txtquangDuongXeHoi;
    private javax.swing.JTextField txtsoLitTauThuy;
    private javax.swing.JTextField txtthoiGianTauThuy;
    private javax.swing.JTextField txtvanTocTauthuy;
    private javax.swing.JTextField txtvanTocXeHoi;
    // End of variables declaration//GEN-END:variables
}
