/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai3;

import java.text.NumberFormat;

/**
 *
 * @author hv
 */
public class FrmShape extends javax.swing.JFrame {

    /**
     * Creates new form FrmShape
     */
    Circle cir;
    Square squ;
    Rectangular rec;
    public FrmShape() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        tbpForm = new javax.swing.JTabbedPane();
        tpRectangular = new javax.swing.JPanel();
        txtRadius = new javax.swing.JTextField();
        txtPerimeterCircle = new javax.swing.JTextField();
        txtAreaCircle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPeriCircle = new javax.swing.JButton();
        btnAreaCircle = new javax.swing.JButton();
        tpSquare = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEdge = new javax.swing.JTextField();
        txtPerimeterSquare = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAreaSquare = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPeriSquare = new javax.swing.JButton();
        btnAreaSquare = new javax.swing.JButton();
        tpCircle = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLength = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtPerimeterRec = new javax.swing.JTextField();
        txtAreaRec = new javax.swing.JTextField();
        btnPerimeterRec = new javax.swing.JButton();
        btnAreaRec = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OOP Shape");

        jLabel1.setText("Radius");

        jLabel2.setText("Perimeter");

        jLabel3.setText("Area");

        btnPeriCircle.setText("Perimeter");
        btnPeriCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriCircleActionPerformed(evt);
            }
        });

        btnAreaCircle.setText("Area");
        btnAreaCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaCircleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpRectangularLayout = new javax.swing.GroupLayout(tpRectangular);
        tpRectangular.setLayout(tpRectangularLayout);
        tpRectangularLayout.setHorizontalGroup(
            tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpRectangularLayout.createSequentialGroup()
                .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tpRectangularLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(46, 46, 46)
                        .addComponent(txtAreaCircle, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                    .addGroup(tpRectangularLayout.createSequentialGroup()
                        .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tpRectangularLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel2))
                            .addGroup(tpRectangularLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPerimeterCircle, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txtRadius))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPeriCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAreaCircle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        tpRectangularLayout.setVerticalGroup(
            tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpRectangularLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tpRectangularLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnPeriCircle))
                    .addGroup(tpRectangularLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPerimeterCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addGap(51, 51, 51)
                .addGroup(tpRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnAreaCircle)
                    .addComponent(txtAreaCircle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        tbpForm.addTab("Circle", tpRectangular);

        jLabel4.setText("Edge");

        jLabel5.setText("Perimeter");

        txtAreaSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaSquareActionPerformed(evt);
            }
        });

        jLabel6.setText("Area");

        btnPeriSquare.setText("Perimeter");
        btnPeriSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeriSquareActionPerformed(evt);
            }
        });

        btnAreaSquare.setText("Area");
        btnAreaSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaSquareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpSquareLayout = new javax.swing.GroupLayout(tpSquare);
        tpSquare.setLayout(tpSquareLayout);
        tpSquareLayout.setHorizontalGroup(
            tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpSquareLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPerimeterSquare, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(txtEdge)
                    .addComponent(txtAreaSquare))
                .addGap(18, 18, 18)
                .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPeriSquare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAreaSquare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        tpSquareLayout.setVerticalGroup(
            tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpSquareLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tpSquareLayout.createSequentialGroup()
                        .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtEdge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPerimeterSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPeriSquare)))
                    .addComponent(jLabel5))
                .addGap(59, 59, 59)
                .addGroup(tpSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnAreaSquare))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tbpForm.addTab("Square", tpSquare);

        jLabel7.setText("Length");

        jLabel8.setText("Width");

        jLabel9.setText("Perimeter");

        jLabel10.setText("Area");

        txtPerimeterRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimeterRecActionPerformed(evt);
            }
        });

        btnPerimeterRec.setText("Perimeter");
        btnPerimeterRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimeterRecActionPerformed(evt);
            }
        });

        btnAreaRec.setText("Area");
        btnAreaRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tpCircleLayout = new javax.swing.GroupLayout(tpCircle);
        tpCircle.setLayout(tpCircleLayout);
        tpCircleLayout.setHorizontalGroup(
            tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpCircleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7))
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLength)
                    .addComponent(txtWidth)
                    .addComponent(txtPerimeterRec)
                    .addComponent(txtAreaRec, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPerimeterRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAreaRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        tpCircleLayout.setVerticalGroup(
            tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpCircleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPerimeterRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerimeterRec))
                .addGap(29, 29, 29)
                .addGroup(tpCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAreaRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAreaRec))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        tbpForm.addTab("Rectangular", tpCircle);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpForm, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpForm)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAreaSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaSquareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaSquareActionPerformed

    private void txtPerimeterRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimeterRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimeterRecActionPerformed

    private void btnPeriCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriCircleActionPerformed
       //tinh chu vi hinh tron
        double radius=Double.parseDouble(txtRadius.getText());
        cir=new Circle(radius);    
        String perimeter=NumberFormat.getInstance().format(cir.calPerimeter());
        txtPerimeterCircle.setText(perimeter);
    }//GEN-LAST:event_btnPeriCircleActionPerformed

    private void btnAreaCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaCircleActionPerformed
        // TODO add your handling code here:
        //tinh dien tich  
        double radius=Double.parseDouble(txtRadius.getText());
        cir=new Circle(radius);    
        String Area=NumberFormat.getInstance().format(cir.calArea());
        txtAreaCircle.setText(Area);
    }//GEN-LAST:event_btnAreaCircleActionPerformed

    private void btnPeriSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeriSquareActionPerformed
        // TODO add your handling code here:
        double edge=Double.parseDouble(txtEdge.getText());
        squ = new Square(edge);
        txtPerimeterSquare.setText(squ.calPerimeter()+" ");
    }//GEN-LAST:event_btnPeriSquareActionPerformed

    private void btnAreaSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaSquareActionPerformed
        // TODO add your handling code here:
         double edge=Double.parseDouble(txtEdge.getText());
        squ = new Square(edge);
        txtAreaSquare.setText(squ.calArea()+"");
    }//GEN-LAST:event_btnAreaSquareActionPerformed

    private void btnPerimeterRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimeterRecActionPerformed
        // TODO add your handling code here:
        double length=Double.parseDouble(txtLength.getText());
        double width=Double.parseDouble(txtWidth.getText());
        rec=new Rectangular(length,width);
        txtPerimeterRec.setText(rec.calPerimeter()+"");
    }//GEN-LAST:event_btnPerimeterRecActionPerformed

    private void btnAreaRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaRecActionPerformed
        // TODO add your handling code here:
        double length=Double.parseDouble(txtLength.getText());
        double width=Double.parseDouble(txtWidth.getText());
        rec=new Rectangular(length,width);
        txtAreaRec.setText(rec.calArea()+" ");
    }//GEN-LAST:event_btnAreaRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmShape().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaCircle;
    private javax.swing.JButton btnAreaRec;
    private javax.swing.JButton btnAreaSquare;
    private javax.swing.JButton btnPeriCircle;
    private javax.swing.JButton btnPeriSquare;
    private javax.swing.JButton btnPerimeterRec;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane tbpForm;
    private javax.swing.JPanel tpCircle;
    private javax.swing.JPanel tpRectangular;
    private javax.swing.JPanel tpSquare;
    private javax.swing.JTextField txtAreaCircle;
    private javax.swing.JTextField txtAreaRec;
    private javax.swing.JTextField txtAreaSquare;
    private javax.swing.JTextField txtEdge;
    private javax.swing.JTextField txtLength;
    private javax.swing.JTextField txtPerimeterCircle;
    private javax.swing.JTextField txtPerimeterRec;
    private javax.swing.JTextField txtPerimeterSquare;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
