/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai5_28_03;

import java.util.Arrays;
import javax.swing.DefaultListModel;

/**
 *
 * @author hv
 */
public class FrmListSort extends javax.swing.JFrame {

    /**
     * Creates new form FrmListSort
     */
    public FrmListSort() {
        initComponents();
        txtListOutPut.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtListInput = new javax.swing.JTextField();
        btnSortString = new javax.swing.JButton();
        btnSortNumber = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListOutPut = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Dãy Số");

        btnSortString.setText("Sắp Xếp Chuỗi");
        btnSortString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortStringActionPerformed(evt);
            }
        });

        btnSortNumber.setText("Sắp Xếp Số");
        btnSortNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortNumberActionPerformed(evt);
            }
        });

        txtListOutPut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtListOutPut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtListOutPut.setSelectionBackground(new java.awt.Color(0, 0, 0));
        txtListOutPut.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(txtListOutPut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtListInput)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSortString, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtListInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSortString)
                    .addComponent(btnSortNumber))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortStringActionPerformed
        // TODO add your handling code here:
       String [] Chuoi=txtListInput.getText().split(",");
       DefaultListModel listmodel= new DefaultListModel();
       for(int i=0;i<Chuoi.length;i++)
       {
           listmodel.addElement(Chuoi[i]);
       }
       Arrays.sort(Chuoi);
       txtListOutPut.setModel(listmodel);
    }//GEN-LAST:event_btnSortStringActionPerformed

    private void btnSortNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortNumberActionPerformed
        // TODO add your handling code here:
         String [] Chuoi=txtListInput.getText().split(",");
         int []number=new int[Chuoi.length];
         //int temp;
         for(int i=0;i<Chuoi.length;i++)
         {
             number[i]=Integer.parseInt(Chuoi[i]);
         }
         Arrays.sort(number);
       DefaultListModel listmodel= new DefaultListModel();
       for(int i=0;i<number.length;i++)
       {
           listmodel.addElement(number[i]);
       }
       txtListOutPut.setModel(listmodel);
        
    }//GEN-LAST:event_btnSortNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSortNumber;
    private javax.swing.JButton btnSortString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtListInput;
    private javax.swing.JList txtListOutPut;
    // End of variables declaration//GEN-END:variables
}
