/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmProduct.java
 *
 * Created on Apr 3, 2015, 10:55:49 PM
 */
package Bai5_28_03;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vostro 3460
 */
public class FrmProduct extends javax.swing.JFrame {

    /** Creates new form FrmProduct */
    ArrayList<Product> listProduct=new ArrayList<>();
    //Product pro;
     DefaultListModel model =new DefaultListModel();
    public FrmProduct() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        InsertPane = new javax.swing.JPanel();
        cbbLoaiSP = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtdonVitinh = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        SearchPane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbbLoaiSanPham = new javax.swing.JComboBox();
        btnSearch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listInfoAll = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbbLoaiSP.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Chon-----", "TAP", "VIET", "SACHGIAOKHOA" }));

        jLabel1.setText("Loại Sản Phẩm");

        jLabel2.setText("Mã Sản Phẩm");

        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setText("Đơn Vị Tính");

        jLabel5.setText("Đơn Giá");

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        txtdonVitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdonVitinhActionPerformed(evt);
            }
        });

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertPaneLayout = new javax.swing.GroupLayout(InsertPane);
        InsertPane.setLayout(InsertPaneLayout);
        InsertPaneLayout.setHorizontalGroup(
            InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPaneLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(84, 84, 84)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdonVitinh, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaSP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.Alignment.LEADING, 0, 165, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        InsertPaneLayout.setVerticalGroup(
            InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertPaneLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdonVitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(InsertPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsert)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Insert Product", InsertPane);

        jLabel6.setText("Loại Sản Phẩm");

        cbbLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-----Chon-----", "TAP", "VIET", "SACHGIAOKHOA" }));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listInfoAll);

        jLabel7.setText("Số Lượng Sản Phẩm");

        javax.swing.GroupLayout SearchPaneLayout = new javax.swing.GroupLayout(SearchPane);
        SearchPane.setLayout(SearchPaneLayout);
        SearchPaneLayout.setHorizontalGroup(
            SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPaneLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(34, 34, 34)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SearchPaneLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(32, 32, 32)
                            .addComponent(cbbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btnSearch)
                            .addGap(47, 47, 47)
                            .addComponent(btnDelete))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        SearchPaneLayout.setVerticalGroup(
            SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch)
                    .addComponent(cbbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SearchPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search", SearchPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtTenSPActionPerformed

private void txtdonVitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdonVitinhActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtdonVitinhActionPerformed

private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
// TODO add your handling code here:
    boolean check=false;
    for(Product pr:listProduct)
    {
        if(pr.maSP.equals(txtmaSP.getText()))
        {
            JOptionPane.showMessageDialog(this,"Ma San Pham Da Co, Nhap Lai !");
            check=true;
            break;
        }
    }
    if(check==true)return;
    String LoaiSP= String.valueOf(cbbLoaiSP.getSelectedItem());
    Product pro=new Product(LoaiSP,txtmaSP.getText(),txtTenSP.getText(),txtdonVitinh.getText(),Double.parseDouble(txtDonGia.getText()));
    listProduct.add(pro);
    Collections.sort(listProduct, pro.ProCompare);
//    model.clear();
//    String chuoi = null;
//    for(int i=0;i<listProduct.size();i++)
//    {
//        chuoi=listProduct.get(i).maSP+" "+listProduct.get(i).tenSP+" "+listProduct.get(i).donviTinh+" "+listProduct.get(i).giaSP;
//        model.addElement(chuoi);
//    }
    JOptionPane.showMessageDialog(this,"Da Them San Pham Moi !");
}//GEN-LAST:event_btnInsertActionPerformed

private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
// TODO add your handling code here:
    //int choose=cbbLoaiSanPham.getSelectedIndex(),number=0;
   
    String item=String.valueOf(cbbLoaiSanPham.getSelectedItem()), chuoi;
  //  String chuoi;
    model.clear();
    int number=0;
    for(Product p:listProduct)
    {
        if(p.loaiSP.equals(item))
        {
            chuoi=p.maSP+" "+p.tenSP+" "+p.donviTinh+" "+p.giaSP+"\n";
            model.addElement(chuoi);
            number++;
        }
    }
    listInfoAll.setModel(model);
    txtNumber.setText(number+"");
    
}//GEN-LAST:event_btnSearchActionPerformed

private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
// TODO add your handling code here:
    String item[]=listInfoAll.getSelectedValue().toString().split(" ");
    String masp_del=item[0];
//    int number=0;
//    int index=cbbLoaiSanPham.getSelectedIndex();
//    listProduct.remove(index);
//    model.remove(index);
    for(Product p:listProduct)
    {
        
        if(p.maSP.equals(masp_del))
        {
            listProduct.remove(p);
            //return;
            break;
              
        }
    }
    model.remove(listInfoAll.getSelectedIndex());
    txtNumber.setText(model.getSize()+"");
    //txtNumber.setText(listInfoAll.size()+" ");
   
}//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmProduct().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InsertPane;
    private javax.swing.JPanel SearchPane;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbbLoaiSP;
    private javax.swing.JComboBox cbbLoaiSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList listInfoAll;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtdonVitinh;
    private javax.swing.JTextField txtmaSP;
    // End of variables declaration//GEN-END:variables
}
