/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai7;

/**
 *
 * @author hv
 */
public class FrmLoginSuccess extends javax.swing.JFrame {

    /**
     * Creates new form FrmLoginSuccess
     */
    public FrmLoginSuccess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mn1 = new javax.swing.JMenu();
        mn_item1 = new javax.swing.JMenuItem();
        mn2 = new javax.swing.JMenu();
        mnuitemProductAdd = new javax.swing.JMenuItem();
        mnuitemProductSearch = new javax.swing.JMenuItem();
        mnuItemProductDelete = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Store");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("WELCOME TO HERE");

        mn1.setText("Account");

        mn_item1.setText("Add new account");
        mn_item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_item1ActionPerformed(evt);
            }
        });
        mn1.add(mn_item1);

        jMenuBar1.add(mn1);

        mn2.setText("Product");

        mnuitemProductAdd.setText("Add New Product");
        mnuitemProductAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemProductAddActionPerformed(evt);
            }
        });
        mn2.add(mnuitemProductAdd);

        mnuitemProductSearch.setText("Search product");
        mnuitemProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemProductSearchActionPerformed(evt);
            }
        });
        mn2.add(mnuitemProductSearch);

        mnuItemProductDelete.setText("Delete product");
        mnuItemProductDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemProductDeleteActionPerformed(evt);
            }
        });
        mn2.add(mnuItemProductDelete);

        jMenuBar1.add(mn2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mn_item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_item1ActionPerformed
        // TODO add your handling code here:
        new frmAddnewAccount().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mn_item1ActionPerformed

    private void mnuitemProductAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemProductAddActionPerformed
        // TODO add your handling code here:
        new frmAddnewProduct().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuitemProductAddActionPerformed

    private void mnuitemProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemProductSearchActionPerformed
        // TODO add your handling code here:
        new frmSearchProduct().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuitemProductSearchActionPerformed

    private void mnuItemProductDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemProductDeleteActionPerformed
        // TODO add your handling code here:
        new FrmDeletePRoduct().setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_mnuItemProductDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoginSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoginSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoginSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoginSuccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLoginSuccess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mn1;
    private javax.swing.JMenu mn2;
    private javax.swing.JMenuItem mn_item1;
    private javax.swing.JMenuItem mnuItemProductDelete;
    private javax.swing.JMenuItem mnuitemProductAdd;
    private javax.swing.JMenuItem mnuitemProductSearch;
    // End of variables declaration//GEN-END:variables
}
