/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai7;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author hv
 */
public class FrmShape extends javax.swing.JFrame {

    /**
     * Creates new form FrmShape
     */
    ShapeManager<Circle> listCircle=new ShapeManager<>();
    ShapeManager<Rectangular> listRectangular=new ShapeManager<>();
    DefaultListModel listModel=new DefaultListModel();
    public FrmShape() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PCircle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRadius = new javax.swing.JTextField();
        btnCircle = new javax.swing.JButton();
        pRectangular = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtlength = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        btnaddRectangular = new javax.swing.JButton();
        PlistShape = new javax.swing.JPanel();
        rbtCircle = new javax.swing.JRadioButton();
        rbRectangular = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtquatityShape = new javax.swing.JTextField();
        txtareaMax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Radius");

        btnCircle.setText("Add Circle");
        btnCircle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCircleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PCircleLayout = new javax.swing.GroupLayout(PCircle);
        PCircle.setLayout(PCircleLayout);
        PCircleLayout.setHorizontalGroup(
            PCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCircleLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(PCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCircle, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PCircleLayout.setVerticalGroup(
            PCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PCircleLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(PCircleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnCircle)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shape Circle", PCircle);

        jLabel2.setText("Length");

        jLabel3.setText("Width");

        btnaddRectangular.setText("Add Rectangular");
        btnaddRectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddRectangularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRectangularLayout = new javax.swing.GroupLayout(pRectangular);
        pRectangular.setLayout(pRectangularLayout);
        pRectangularLayout.setHorizontalGroup(
            pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRectangularLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtWidth)
                    .addComponent(btnaddRectangular, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtlength))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pRectangularLayout.setVerticalGroup(
            pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRectangularLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtlength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pRectangularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnaddRectangular)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Shape Rectangular", pRectangular);

        buttonGroup1.add(rbtCircle);
        rbtCircle.setText("Shape Circle");

        buttonGroup1.add(rbRectangular);
        rbRectangular.setText("Shape Rectangular");

        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Quatity Shape");

        jLabel5.setText("Area Max");

        javax.swing.GroupLayout PlistShapeLayout = new javax.swing.GroupLayout(PlistShape);
        PlistShape.setLayout(PlistShapeLayout);
        PlistShapeLayout.setHorizontalGroup(
            PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlistShapeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(PlistShapeLayout.createSequentialGroup()
                        .addComponent(rbtCircle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbRectangular))
                    .addGroup(PlistShapeLayout.createSequentialGroup()
                        .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtquatityShape)
                            .addComponent(txtareaMax))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        PlistShapeLayout.setVerticalGroup(
            PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlistShapeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRectangular)
                    .addComponent(rbtCircle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtquatityShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PlistShapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtareaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("List Shape", PlistShape);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCircleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCircleActionPerformed
        // TODO add your handling code here:
        double radius=Double.parseDouble(txtRadius.getText());
        Circle cr=new Circle(radius);
        
        listCircle.addHinh(cr);
        JOptionPane.showMessageDialog(rootPane,"Successfull !");
    }//GEN-LAST:event_btnCircleActionPerformed

    private void btnaddRectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddRectangularActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnaddRectangularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmShape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmShape().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PCircle;
    private javax.swing.JPanel PlistShape;
    private javax.swing.JButton btnCircle;
    private javax.swing.JButton btnaddRectangular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pRectangular;
    private javax.swing.JRadioButton rbRectangular;
    private javax.swing.JRadioButton rbtCircle;
    private javax.swing.JTextField txtRadius;
    private javax.swing.JTextField txtWidth;
    private javax.swing.JTextField txtareaMax;
    private javax.swing.JTextField txtlength;
    private javax.swing.JTextField txtquatityShape;
    // End of variables declaration//GEN-END:variables
}
