/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmNhanVien.java
 *
 * Created on Mar 15, 2015, 1:20:04 PM
 */
package Bai2;

import javax.swing.JOptionPane;

/**
 *
 * @author Vostro 3460
 */
public class FrmNhanVien extends javax.swing.JFrame {

    /** Creates new form FrmNhanVien */
    NhanVien NV;
    NhanVienVP NVVP;
    NhanVienSX NVSX;
    
    public FrmNhanVien() {
      
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTangCa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtHeSoLuong = new javax.swing.JTextField();
        cbbLoaiNhanVien = new javax.swing.JComboBox();
        txtSoSanPham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayVaoLam = new javax.swing.JTextField();
        txtSoCon = new javax.swing.JTextField();
        txtSoNgayVang = new javax.swing.JTextField();
        cbbGioiTinh = new javax.swing.JComboBox();
        rdbTangCa = new javax.swing.JRadioButton();
        rdbKhongTangCa = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHienThi = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTienLuong = new javax.swing.JTextField();
        txtTroCap = new javax.swing.JTextField();
        txtThucLinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("THÔNG TIN NHÂN VIÊN");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Họ Tên");

        jLabel2.setText("Ngày Sinh");

        jLabel3.setText("Hệ Số Lương");

        jLabel4.setText("Loại Nhân Viên");

        txtHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoTenActionPerformed(evt);
            }
        });

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        cbbLoaiNhanVien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nhân Viên Văn Phòng", "Nhân Viên Sản Xuất" }));

        jLabel5.setText("Số Sản Phẩm");

        jLabel6.setText("Giới Tính");

        jLabel7.setText("Ngày Vào Làm");

        jLabel8.setText("Số Con");

        jLabel9.setText("Số Ngày Vắng");

        cbbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        btgTangCa.add(rdbTangCa);
        rdbTangCa.setText("Tăng Ca");

        btgTangCa.add(rdbKhongTangCa);
        rdbKhongTangCa.setText("Không Tăng Ca");

        jButton1.setText("Hiển Thị Thông Tin - Tính Lương");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtHienThi.setColumns(20);
        txtHienThi.setRows(5);
        jScrollPane1.setViewportView(txtHienThi);

        jLabel10.setText("Thông Tin Nhân Viên");

        jLabel11.setText("Tiền Lương");

        jLabel12.setText("Trợ Cấp");

        jLabel13.setText("Thực Lĩnh");

        txtTienLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTienLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienLuongActionPerformed(evt);
            }
        });

        txtTroCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTroCapActionPerformed(evt);
            }
        });

        txtThucLinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThucLinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(txtSoSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(cbbLoaiNhanVien, 0, 137, Short.MAX_VALUE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtSoCon)
                            .addComponent(txtSoNgayVang)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbTangCa)
                        .addGap(40, 40, 40)
                        .addComponent(rdbKhongTangCa)))
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThucLinh))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTroCap, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(cbbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtSoCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtSoNgayVang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbTangCa)
                        .addComponent(rdbKhongTangCa)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtTroCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtThucLinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

private void txtHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoTenActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtHoTenActionPerformed

private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtNgaySinhActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    if(txtHoTen.getText().equals("")|| txtNgaySinh.getText().equals("") || txtHeSoLuong.getText().equals("") || txtNgayVaoLam.getText().equals("") || txtSoNgayVang.getText().equals("") || txtSoCon.getText().equals("")) 
    {
        JOptionPane.showMessageDialog(this,"Vui Lòng Nhập Đầy đủ thông tin !");
        return;
    }
    txtTienLuong.enable(false);
    txtTroCap.enable(false);
    txtThucLinh.enable(false);
    String hoTen=txtHoTen.getText();
    String ngaySinh=txtNgaySinh.getText();
    String ngayVaoLam=txtNgayVaoLam.getText();
    float hesoluong=Float.parseFloat(txtHeSoLuong.getText());
    int soSanPham=0,soCon,soNgayVang;
    soCon=Integer.parseInt(txtSoCon.getText());
    soNgayVang=Integer.parseInt(txtSoNgayVang.getText());
    boolean gioiTinh=false,tangCa=false;
    double tienLuong,troCap,thucLinh;
    String chuoi="";
    
    if(cbbGioiTinh.getSelectedIndex()==0)
    {
        gioiTinh=true;
    }
    else
    {
        gioiTinh=false;
    }
    NV=new NhanVien(hoTen, ngaySinh, gioiTinh, ngayVaoLam, hesoluong, soCon);
     chuoi+="Họ Tên: "+hoTen+"\nNgày Sinh: "+ngaySinh+"\nGiới Tính: "+cbbGioiTinh.getSelectedItem()+"\nNgày Vào Làm:"+ngayVaoLam+"\nHệ số Lương: "+hesoluong+"\n";
    if(cbbLoaiNhanVien.getSelectedIndex()==0)
    {
        NVVP=new NhanVienVP(soNgayVang, hoTen, ngaySinh, gioiTinh, ngayVaoLam, hesoluong, soCon);
        tienLuong=NVVP.tinhTienLuong();
        troCap=NVVP.tinhTroCap();
        thucLinh=tienLuong+troCap;
        txtTienLuong.setText(tienLuong+"");
        txtTroCap.setText(troCap+"");
        txtThucLinh.setText(thucLinh+"");
        chuoi+="Loại Nhân Viên: "+cbbLoaiNhanVien.getSelectedItem();
        txtHienThi.setText(chuoi);
        
        
    }
    else
    {
        soSanPham=Integer.parseInt(txtSoSanPham.getText());
        NVSX=new NhanVienSX(soSanPham, hoTen, ngaySinh, gioiTinh, ngayVaoLam, hesoluong, soCon);
        if(btgTangCa.getSelection().equals(rdbTangCa.getModel()))
            tangCa=true;
        else
            tangCa=false;
        tienLuong=NVSX.tinhTienLuong();
        troCap=NVSX.tinhTroCap(tangCa);
        thucLinh=tienLuong+troCap;
        txtTienLuong.setText(tienLuong+"");
        txtTroCap.setText(troCap+"");
        txtThucLinh.setText(thucLinh+"");
        chuoi+="Loại Nhân Viên: "+cbbLoaiNhanVien.getSelectedItem();
        txtHienThi.setText(chuoi);
         
    }
}//GEN-LAST:event_jButton1ActionPerformed

private void txtTienLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienLuongActionPerformed
// TODO add your handling code here:
     
}//GEN-LAST:event_txtTienLuongActionPerformed

private void txtThucLinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThucLinhActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_txtThucLinhActionPerformed

private void txtTroCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTroCapActionPerformed
// TODO add your handling code here:
     
}//GEN-LAST:event_txtTroCapActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
               
                new FrmNhanVien().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTangCa;
    private javax.swing.JComboBox cbbGioiTinh;
    private javax.swing.JComboBox cbbLoaiNhanVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbKhongTangCa;
    private javax.swing.JRadioButton rdbTangCa;
    private javax.swing.JTextField txtHeSoLuong;
    private javax.swing.JTextArea txtHienThi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSoCon;
    private javax.swing.JTextField txtSoNgayVang;
    private javax.swing.JTextField txtSoSanPham;
    private javax.swing.JTextField txtThucLinh;
    private javax.swing.JTextField txtTienLuong;
    private javax.swing.JTextField txtTroCap;
    // End of variables declaration//GEN-END:variables
}
