/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPhepTinh.java
 *
 * Created on Mar 15, 2015, 12:39:37 PM
 */
package Bai2;

import java.text.NumberFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Vostro 3460
 */
public class FrmPhepTinh extends javax.swing.JFrame {

    /** Creates new form FrmPhepTinh */
    PhepTinh Pt;
    float soA;
    float soB;
    
    public FrmPhepTinh() {
        initComponents();
        txtKQ.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKQ = new javax.swing.JTextField();
        btnTong = new javax.swing.JButton();
        btnHieu = new javax.swing.JButton();
        btnTich = new javax.swing.JButton();
        btnThuong = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phép Tính");

        jLabel1.setText("Số A");

        jLabel2.setText("Số B");

        txtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAActionPerformed(evt);
            }
        });

        jLabel3.setText("Kết Quả");

        txtKQ.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtKQ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtKQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKQActionPerformed(evt);
            }
        });

        btnTong.setText("Tổng");
        btnTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongActionPerformed(evt);
            }
        });

        btnHieu.setText("Hiệu");
        btnHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHieuActionPerformed(evt);
            }
        });

        btnTich.setText("Tích");
        btnTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTichActionPerformed(evt);
            }
        });

        btnThuong.setText("Thương");
        btnThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuongActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKQ, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(txtA, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(txtB, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnReset)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnTong))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnHieu)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnTich)
                        .addGap(27, 27, 27)
                        .addComponent(btnThuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtKQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addComponent(btnReset)
                .addGap(23, 23, 23))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents
private void btnThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuongActionPerformed
// TODO add your handling code here:
   
  
    if(txtA.getText().equals("") || txtB.getText().equals(""))
    {
        JOptionPane.showMessageDialog(this,"Ô Còn Trống, Vui Lòng Nhập Đầy Đủ !");
        return;
    }
    Pattern p=Pattern.compile("[0-9]+");
    Matcher m=p.matcher(txtB.getText());
    Matcher n=p.matcher(txtA.getText());
    if(!m.matches() || !n.matches())
    {
        JOptionPane.showMessageDialog(this,"Nhập Số Không Nhập Chữ !");
        return;
    }
    soA=Float.parseFloat(txtA.getText());
    soB=Float.parseFloat(txtB.getText());
    if(soB==0)
    {
        JOptionPane.showMessageDialog(this,"Phép Chia Không Chia Cho Thương");
        return;
    }
    Pt=new PhepTinh(soA, soB);
   // Pt.tinhTong();
    String ketQua=NumberFormat.getInstance().format(Pt.tinhThuong());
    txtKQ.setText(ketQua);
}//GEN-LAST:event_btnThuongActionPerformed

private void btnTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTongActionPerformed
// TODO add your handling code here:
        if(txtA.getText().equals("") || txtB.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ô Còn Trống, Vui Lòng Nhập Đầy Đủ !");
            return;
        }
        Pattern p=Pattern.compile("[0-9]+");
        Matcher m=p.matcher(txtB.getText());
        Matcher n=p.matcher(txtA.getText());
        if(!m.matches() || !n.matches())
        {
            JOptionPane.showMessageDialog(this,"Nhập Số Không Nhập Chữ !");
            return;
        }
    soA=Float.parseFloat(txtA.getText());
    soB=Float.parseFloat(txtB.getText());
    Pt=new PhepTinh(soA, soB);
   // Pt.tinhTong();
    txtKQ.setText(Pt.tinhTong()+"" );
}//GEN-LAST:event_btnTongActionPerformed

private void txtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtAActionPerformed

private void btnHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHieuActionPerformed
// TODO add your handling code here:
        if(txtA.getText().equals("") || txtB.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ô Còn Trống, Vui Lòng Nhập Đầy Đủ !");
            return;
        }
        Pattern p=Pattern.compile("[0-9]+");
        Matcher m=p.matcher(txtB.getText());
        Matcher n=p.matcher(txtA.getText());
        if(!m.matches() || !n.matches())
        {
            JOptionPane.showMessageDialog(this,"Nhập Số Không Nhập Chữ !");
            return;
        }
    soA=Float.parseFloat(txtA.getText());
    soB=Float.parseFloat(txtB.getText());
    Pt=new PhepTinh(soA, soB);
   // Pt.tinhTong();
    txtKQ.setText(Pt.tinhHieu()+"" );
}//GEN-LAST:event_btnHieuActionPerformed

private void btnTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTichActionPerformed
// TODO add your handling code here:
        if(txtA.getText().equals("") || txtB.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ô Còn Trống, Vui Lòng Nhập Đầy Đủ !");
            return;
        }
        Pattern p=Pattern.compile("[0-9]+");
        Matcher m=p.matcher(txtB.getText());
        Matcher n=p.matcher(txtA.getText());
        if(!m.matches() || !n.matches())
        {
            JOptionPane.showMessageDialog(this,"Nhập Số Không Nhập Chữ !");
            return;
        }
    soA=Float.parseFloat(txtA.getText());
    soB=Float.parseFloat(txtB.getText());
    Pt=new PhepTinh(soA, soB);
   // Pt.tinhTong();
    txtKQ.setText(Pt.tinhTich()+"" );
}//GEN-LAST:event_btnTichActionPerformed

private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
// TODO add your handling code here:
    txtA.setText(null);
    txtB.setText(null);
    txtKQ.setText(null);
}//GEN-LAST:event_btnResetActionPerformed

private void txtKQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKQActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtKQActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPhepTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPhepTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPhepTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPhepTinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmPhepTinh().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHieu;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThuong;
    private javax.swing.JButton btnTich;
    private javax.swing.JButton btnTong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtKQ;
    // End of variables declaration//GEN-END:variables

    private void temlate() {
       // throw new UnsupportedOperationException("Not yet implemented");
        if(txtA.getText().equals("") || txtB.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Ô Còn Trống, Vui Lòng Nhập Đầy Đủ !");
            return;
        }
        Pattern p=Pattern.compile("[0-9]+");
        Matcher m=p.matcher(txtB.getText());
        Matcher n=p.matcher(txtA.getText());
        if(!m.matches() || !n.matches())
        {
            JOptionPane.showMessageDialog(this,"Nhập Số Không Nhập Chữ !");
            return;
        }
    }
}
