/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmTranDanh.java
 *
 * Created on Mar 18, 2015, 8:50:50 PM
 */
package Bai2;

import javax.swing.JOptionPane;

/**
 *
 * @author Vostro 3460
 */
public class frmTranDanh extends javax.swing.JFrame {

    /** Creates new form frmTranDanh */
    NguoiLinh NL;
    BoBinh BB;
    KyBinh KB;
    boolean result=false;
    private int tempBB; 
    private int tempKb;
   
    public frmTranDanh() {
        
        initComponents();
        btnBB.setEnabled(false);
        btnKB.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbBB = new javax.swing.JLabel();
        lbKB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenBB = new javax.swing.JTextField();
        txtSucManhBB = new javax.swing.JTextField();
        txtVuKhiBB = new javax.swing.JTextField();
        txtTenKB = new javax.swing.JTextField();
        txtSucManhKB = new javax.swing.JTextField();
        txtVuKhiKB = new javax.swing.JTextField();
        btnKhoiTao = new javax.swing.JButton();
        btnBB = new javax.swing.JButton();
        btnKB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Trận Đánh");
        setAlwaysOnTop(true);

        lbBB.setText("Lính Bộ Binh");

        lbKB.setText("Lính Kỵ Binh");

        jLabel3.setText("Tên");

        jLabel4.setText("Sức Mạnh");

        jLabel5.setText("Vũ Khí");

        jLabel6.setText("Tên");

        jLabel7.setText("Sức Mạnh");

        jLabel8.setText("Vũ Khí");

        btnKhoiTao.setText("Khởi Tạo");
        btnKhoiTao.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        btnKhoiTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoiTaoActionPerformed(evt);
            }
        });

        btnBB.setText("Bộ Binh Đánh");
        btnBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBBActionPerformed(evt);
            }
        });

        btnKB.setText("Kỵ Binh Đánh");
        btnKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("TRẬN ĐÁNH");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenBB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVuKhiBB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSucManhBB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnKhoiTao, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(btnKB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTenKB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSucManhKB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtVuKhiKB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbBB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbKB)
                                .addGap(35, 35, 35))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(221, 221, 221))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBB, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKB))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnKhoiTao))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSucManhBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSucManhKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnBB))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtVuKhiBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVuKhiKB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnKB))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents
private void btnKhoiTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiTaoActionPerformed
// TODO add your handling code here:
   
    String tenBoBinh=txtTenBB.getText();
    String TsucManhBB=txtSucManhBB.getText();
    String vukhiBB=txtVuKhiBB.getText();
   // int ta=[^!1-9];
//------------------------------------------------------------------------------
    String tenKyBinh=txtTenKB.getText();
    String TsucManhKB=txtSucManhKB.getText();
    String vukhiKB=txtVuKhiKB.getText();
    
    if(tenBoBinh.equals("") || TsucManhBB.equals("") || vukhiBB.equals("") || tenKyBinh.equals("") || TsucManhKB.equals("") || vukhiKB.equals(""))
    {
        JOptionPane.showMessageDialog(this,"Bộ Binh Hoặc Kị Binh chưa Được Khởi Tạo Đầy Đủ !");
        btnBB.setEnabled(false);
        btnKB.setEnabled(false);
    }
    else
    {
        int A=Integer.parseInt(TsucManhBB);
        if(Integer.parseInt(TsucManhBB)/1!=A)
        {
            JOptionPane.showMessageDialog(this,"Suc Manh Bo Binh Phai La so !");
        }
        int sucManhBB=Integer.parseInt(TsucManhBB);
        int sucManhKB=Integer.parseInt(TsucManhKB);
        BB=new BoBinh(sucManhBB,vukhiBB);
        KB=new KyBinh(sucManhKB, vukhiKB);
        JOptionPane.showMessageDialog(this,"Bộ Binh: "+tenBoBinh+",Sức Mạnh "+sucManhBB+",Vũ Khí: "+vukhiBB+"\n"+"Kỵ Binh: "+tenKyBinh+",Sức Mạnh "+sucManhKB+",Vũ Khí: "+vukhiKB);
        //--------------tat button khoi tao an khỏi màn hình -------------------
        btnKhoiTao.setVisible(false);
        //----------------------------------------------------------------------
        btnBB.setEnabled(true);
        btnKB.setEnabled(true);
        //----------------------------------------------------------------------
        result=true;
    }
   
   
  
}//GEN-LAST:event_btnKhoiTaoActionPerformed
    
private void btnBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBBActionPerformed
// TODO add your handling code here:
    
   
    tempBB=BB.getSucManh();
    tempKb=KB.getSucManh();
    if(tempKb<=0)
    {
        
        if(tempBB<=0)
        {
            JOptionPane.showMessageDialog(this,"Lưỡng Bại Câu Thương !");
        }
        else
        {
             JOptionPane.showMessageDialog(this,"Kỵ Binh Đã Thua !");
        }
    }
    else
    {
        if(tempBB>0)
        {

            tempBB=BB.chienDau();
        }
        if(tempBB>0  )
        {
            //----thay đổi chỉ số trực tiếp trên form
                txtSucManhBB.setText(tempBB+"");
            //----show bảng thông báo chỉ số thay đổi của Kỵ binh và Bộ Binh
              //JOptionPane.showMessageDialog(this,"Bộ Binh "+tempBB+" - Kỵ Binh "+tempKb);
        }
        else
        {
            //----thay đổi chỉ số trực tiếp trên form
            txtSucManhBB.setText(tempBB+"");
            //----show bảng thông báo chỉ số thay đổi của Kỵ binh và Bộ Binh
            JOptionPane.showMessageDialog(this,"Bộ Binh Đã Thua, Không đánh được nữa !");
        }   
    }
}//GEN-LAST:event_btnBBActionPerformed

private void btnKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKBActionPerformed
// TODO add your handling code here:
     tempBB=BB.getSucManh();
     tempKb=KB.getSucManh();
    if(tempBB<=0)
    {
       if(tempKb<=0)
        {
            JOptionPane.showMessageDialog(this,"Lưỡng Bại Câu Thương !");
        }
        else
        {
             JOptionPane.showMessageDialog(this,"Bộ Binh Đã Thua !");
        }  
    }
    else
    {
        
        if(tempKb>0)
        {

            tempKb=KB.chienDau();
        }
        if(tempKb>0  )
        {
            //----thay đổi chỉ số trực tiếp trên form
            txtSucManhKB.setText(tempKb+"");
            //----show bảng thông báo chỉ số thay đổi của Kỵ binh và Bộ Binh
            //  JOptionPane.showMessageDialog(this,"Bộ Binh "+tempBB+" - Kỵ Binh "+tempKb);
        }
        else
        {
            //----thay đổi chỉ số trực tiếp trên form
            txtSucManhKB.setText(tempKb+"");
            //----show bảng thông báo chỉ số thay đổi của Kỵ binh và Bộ Binh
            JOptionPane.showMessageDialog(this,"Kỵ Binh Đã Thua, Không đánh được nữa !");
        }   
    }
}//GEN-LAST:event_btnKBActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    
    btnKhoiTao.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTranDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTranDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTranDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTranDanh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmTranDanh().setVisible(true);
               
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBB;
    private javax.swing.JButton btnKB;
    private javax.swing.JButton btnKhoiTao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbBB;
    private javax.swing.JLabel lbKB;
    private javax.swing.JTextField txtSucManhBB;
    private javax.swing.JTextField txtSucManhKB;
    private javax.swing.JTextField txtTenBB;
    private javax.swing.JTextField txtTenKB;
    private javax.swing.JTextField txtVuKhiBB;
    private javax.swing.JTextField txtVuKhiKB;
    // End of variables declaration//GEN-END:variables
}
